"""fix aulet table 1

Revision ID: 374ffb8b0318
Revises: cdb4e99a7979
Create Date: 2025-08-17 02:43:46.216407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '374ffb8b0318'
down_revision: Union[str, None] = 'cdb4e99a7979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aulet', sa.Column('birthday', sa.DateTime(), nullable=False))
    op.add_column('aulet', sa.Column('death_date', sa.DateTime(), nullable=True))
    op.drop_column('aulet', 'birthday_date')
    op.drop_column('aulet', 'death_date_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aulet', sa.Column('death_date_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('aulet', sa.Column('birthday_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('aulet', 'death_date')
    op.drop_column('aulet', 'birthday')
    # ### end Alembic commands ###
