"""fix tree

Revision ID: 592a166e14ee
Revises: a938fd3dddf4
Create Date: 2025-09-03 04:39:13.250251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592a166e14ee'
down_revision: Union[str, None] = 'a938fd3dddf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tree', 't_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tree', 't_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
