"""fix aulet table

Revision ID: cdb4e99a7979
Revises: aedd050bcdc2
Create Date: 2025-08-17 02:43:14.971069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb4e99a7979'
down_revision: Union[str, None] = 'aedd050bcdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aulet', sa.Column('birthday_date', sa.DateTime(), nullable=False))
    op.add_column('aulet', sa.Column('death_date_date', sa.DateTime(), nullable=True))
    op.drop_column('aulet', 'death_date')
    op.drop_column('aulet', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aulet', sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('aulet', sa.Column('death_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('aulet', 'death_date_date')
    op.drop_column('aulet', 'birthday_date')
    # ### end Alembic commands ###
