"""fix unical

Revision ID: ec8ca7fa3c3a
Revises: 374ffb8b0318
Create Date: 2025-08-25 18:15:12.483140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8ca7fa3c3a'
down_revision: Union[str, None] = '374ffb8b0318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tree_name_key'), 'tree', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tree_name_key'), 'tree', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
