"""tariff table fix

Revision ID: eeb1795af8f0
Revises: badfd4dde57d
Create Date: 2025-06-13 00:07:37.079457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb1795af8f0'
down_revision: Union[str, None] = 'badfd4dde57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family')
    op.add_column('user_tariffs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_tariffs', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('user_tariffs', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tariffs', 'end_date')
    op.drop_column('user_tariffs', 'start_date')
    op.drop_column('user_tariffs', 'is_active')
    op.create_table('family',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_alive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('death_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('father_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mother_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partners_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('family_pkey'))
    )
    # ### end Alembic commands ###
